name: Build and Deploy Fabric Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Grant execute permissions and build
      - name: Build the jar
        run: |
          chmod +x gradlew
          ./gradlew build

      # Step 4: Archive the build artifacts
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: fabric-plugin-jar
          path: build/libs/*.jar


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download the jar artifact
      - name: Download jar artifact
        uses: actions/download-artifact@v3
        with:
          name: fabric-plugin-jar

      # Step 2: Package it into the Minecraft server container
      - name: Deploy to server
        env:
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp -i $SSH_PRIVATE_KEY fabric-plugin-jar/*.jar user@${SERVER_ADDRESS}:/path/to/server/plugins/
          ssh -i $SSH_PRIVATE_KEY user@${SERVER_ADDRESS} "cd /path/to/server && ./restart_server.sh"
